# allows to recompile core and other standard library crates on demand
[unstable]
build-std = ["core", "compiler_builtins"]


# Adds needed functions
[dependencies]
rlibc = "1.0.0"


[build]
target = "x86_64-rust_os.json"